[package]
name = "fudge"
version = "0.0.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fudge-core = { path = "../core"}
fudge-companion = { path = "../core/src/builder/companion"}

polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.24" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
