[package]
name = "integration_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fudge = { path = "../fudge" }
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
centrifuge-runtime = {git = "https://github.com/centrifuge/centrifuge-chain", rev = "ea784b0a08b480d4a9738160bfa9068c1be811e2"}
polkadot-runtime = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.24" }
polkadot-core-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.24" }
sp-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-tracing = { git = "https://github.com/paritytech/substrate", default-features = true, branch = "polkadot-v0.9.24" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
