[package]
name = "fudge-companion"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.83", features = ["full", "extra-traits"] }
quote = "1.0.14"
proc-macro2 = "1.0.36"
proc-macro-crate = "1.1.0"